# -*- coding: utf-8 -*-
"""dz_topic_4_svertoka_viktor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHpUQberbRwT1cTdur0ZKVvDy1wOYhwP
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Якщо на Kaggle: встановіть kaggle API, авторизуйтеся і завантажте датасет
!pip install -q kagglehub
import kagglehub

# Завантаження
path = kagglehub.dataset_download("mchilamwar/predict-concrete-strength")

# Завантаження даних
df = pd.read_csv("ConcreteStrengthData.csv")

# Ознайомлення з даними
df.head()
df.info()
df.describe()
sns.pairplot(df)

# Цільова змінна — міцність бетону (last column)
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Розділення на тренувальний і тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Нормалізація
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Перетворення у тензори
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# Створення DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Клас нейронної мережі
class ConcreteNet(nn.Module):
    def __init__(self):
        super(ConcreteNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(8, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)

model = ConcreteNet()

# Функція втрат та оптимізатор
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Навчання
epochs = 100
losses = []

for epoch in range(epochs):
    epoch_loss = 0
    for inputs, targets in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    losses.append(epoch_loss / len(train_loader))
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {epoch_loss/len(train_loader):.4f}")

plt.plot(losses)
plt.xlabel("Epoch")
plt.ylabel("Loss (MSE)")
plt.title("Навчання моделі")
plt.grid(True)
plt.show()

model.eval()
with torch.no_grad():
    y_pred = model(X_test_tensor).numpy()

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse:.2f}")
print(f"MAE: {mae:.2f}")
print(f"R^2: {r2:.2f}")

plt.figure(figsize=(10,6))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.xlabel("Фактична міцність")
plt.ylabel("Прогнозована міцність")
plt.title("Фактичні vs Прогнозовані значення")
plt.grid(True)
plt.show()

print("""
📌 Висновки

🔹 MSE = 41.84 — це **хороший результат**: модель досить точно прогнозує міцність бетону, хоча залишився простір для подальшої оптимізації.

🔹 MAE = 5.17 — це значення знаходиться **на межі між хорошим і відмінним рівнем**, тобто в середньому модель помиляється на ~5 одиниць міцності.

🔹 R² = 0.84 — це **відмінний результат**, який вказує, що модель добре пояснює варіацію в даних і має високу прогностичну здатність.

📊 Аналіз кореляції ознак показує, що найбільший вплив на прогнозовану міцність мають такі компоненти як Cement, Age та Water. Це узгоджується з будівельними нормами та очікуваннями.
""")